# Generated by Django 3.0.6 on 2020-05-26 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowerwModel',
        ),
    ]
